apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-gke-agent
spec:
  replicas: 5
  selector:
    app: jenkins-gke-agent
  template:
    metadata:
      name: jenkins-gke-agent
      labels:
        app: jenkins-gke-agent
    spec:
      containers:
        - name: jenkins-gke-agent
          image: gcr.io/ansible-tower-engineering/jenkins-swarm-agent
          imagePullPolicy: Always
          command: ["/bin/bash","-c"]
          args:
            - 'java -jar swarm-client-jar-with-dependencies.jar -master=http://jenkins.testing.ansible.com -username=${JENKINS_USER} -password=${JENKINS_TOKEN} -executors=1 -mode=exclusive -labels=gke-swarm'
          env:
            - name: DOCKER_HOST
              value: 'tcp://localhost:2375'

            - name: ANSIBLE_HOST_KEY_CHECKING
              value: 'False'

            - name: ANSIBLE_BECOME_METHOD
              value: 'sudo'

            - name: ANSIBLE_SSH_CONTROL_PATH
              value: '%(directory)s/%%h-%%r'

            - name: JENKINS_USER
              valueFrom:
                secretKeyRef:
                  name: jenkins-credentials
                  key: jenkins-user

            - name: JENKINS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jenkins-credentials
                  key: jenkins-token

        - name: docker-daemon
          image: docker:1.12-dind
          resources:
            limits:
              memory: 2.5Gi
          securityContext:
            privileged: true
