---
version: '2'
services:
  test_tower_ui:
    image: gcr.io/ansible-tower-engineering/tower-qe
    environment:
      PYTEST_ADDOPTS:
    volumes:
      - '../../..:/tower-qa'
      # a local checkout of towerkit may be mounted and used for test runs:
      # - '../relative/path/to/towerkit:/towerkit'
    links:
      - chrome_local
    external_links:
      - 'tools_tower_1:tower'
    command: py.test -c tools/docker/ui/pytest.ini tests/ui
  chrome_local:
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    expose:
      - "4444"
      - "5900"
    ports:
      - "5901:5900"
networks:
  default:
    external:
      name: tools_default
