version: '2'
services:
  pytest_sauce:
    build:
      context: ../../../
      dockerfile: tools/docker/ui/Dockerfile
    environment:
      SAUCELABS_USERNAME:
      SAUCELABS_API_KEY:
      PYTEST_ADDOPTS: '-m ui -k test'
    entrypoint: tools/docker/ui/pytest_sauce.sh
