---
version: '2'
services:
  pytest:
    image: gcr.io/ansible-tower-engineering/tower-qe
    build:
      context: ../../../
      dockerfile: tools/docker/ui/Dockerfile
    environment:
      PYTEST_ADDOPTS:
    volumes:
      - '../../..:/tower-qa'
    entrypoint: py.test
  pytest_sauce:
    extends:
      service: pytest
    environment:
      SAUCELABS_USERNAME:
      SAUCELABS_API_KEY:
    entrypoint: tools/docker/ui/pytest_sauce.sh
