---
- block:

    - name: Install required dracut related packages
      package:
        name: '{{ item }}'
      become: True
      loop:
        - dracut-fips
        - dracut-fips-aesni

    - name: Regenerate the initramfs file
      command: dracut -v -f
      become: True

    - name: Add fips=1 to GRUB_CMDLINE_LINUX
      lineinfile:
        path: /etc/default/grub
        regexp: 'GRUB_CMDLINE_LINUX="(.*)"'
        line: 'GRUB_CMDLINE_LINUX="fips=1 \1"'
        backrefs: yes
      become: True

    - name: Apply the changes to /etc/default/grub
      shell: grub2-mkconfig -o /boot/grub2/grub.cfg
      become: True

    - name: reboot
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

  when: not ansible_fips and ansible_os_family == 'RedHat'
