---

- name: update yum
  yum:
    name: yum
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: update apt
  apt:
    pkg: apt
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: install haproxy
  apt:
    pkg: haproxy
    state: latest
  when: ansible_pkg_mgr == 'apt'

- name: install haproxy
  yum:
    name: haproxy
    state: latest
  when: ansible_pkg_mgr == 'yum'

- name: upload haproxy cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: create stat socket directory
  file:
    path: /run/haproxy/
    state: directory
    mode: 777

- name: allow nonlocal bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    state: present

- name: allow haproxy bind any selinux policy
  seboolean:
    name: haproxy_connect_any
    state: yes

- name: generate ssl key
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout /etc/awx.key -out /etc/awx.crt

- name: generate pem file
  shell: cat /etc/awx.crt /etc/awx.key > /etc/awx.pem

- name: start haproxy
  service:
    name: haproxy
    state: started
