---
- hosts: localhost
  vars:
    cli_repo_dest: /etc/yum.repos.d/ansible-tower-cli.repo
  tasks:
    - name: Enable ansible-tower nightlies repo
      get_url:
        url: "{{ aw_repo_url }}/cli/ansible-tower-cli-el{{ ansible_distribution_major_version }}.repo"
        dest: "{{ cli_repo_dest }}"

    - name: Patch aw_repo_url
      lineinfile:
        backrefs: yes
        regexp: "^baseurl"
        line: "baseurl={{ aw_repo_url }}/rpm/epel-7-$basearch"
        path: "{{ cli_repo_dest }}"
