---
- hosts: test-runner
  tasks:
    - name: Ensure the artifacts directory exist
      file:
        path: '{{ lookup("env", "PWD") }}/artifacts'
        state: directory
      delegate_to: localhost

    - name: Retrieve artifacts from test runner
      fetch:
        src: '~/tower-qa/playbooks/all_tower_logs.tar.gz'
        dest: '{{ lookup("env", "PWD") }}/artifacts/all_tower_logs.tar.gz'
        flat: yes
