---
- hosts: test-runner
  tasks:
    - name: Run Integration Tests
      command: ./tools/jenkins/scripts/test.sh
      args:
        chdir: ~/tower-qa
      environment:
        TESTEXPR: '{{ lookup("env", "TESTEXPR") }}'
        TOWERKIT_BRANCH: '{{ lookup("env", "TOWERKIT_BRANCH") }}'

    - name: Ensure the artifacts directory exist
      file:
        path: '{{ lookup("env", "PWD") }}/artifacts'
        state: directory
      delegate_to: localhost

    - name: Retrieve junit results
      fetch:
        src: ~/tower-qa/reports/junit/results-final.xml
        dest: '{{ lookup("env", "PWD") }}/artifacts/results.xml'
        flat: true
