# Tasks to collect remote artifacts on tower server

- name: collect the name of log files
  find: 
    paths: ['{{ tower_log_dir }}', '{{ supervisor_log_dir }}']
    recurse: no
  become: yes
  become_method: sudo
  register: log_files_to_copy

- name: fetch tower log files
  fetch: 
    src: '{{ item.path }}'
    dest: '{{ local_tower_artifacts_dir }}/'
  become: yes
  become_method: sudo
  with_items: '{{ log_files_to_copy.files }}'
