---

- name: delete existing azure instance(s)
  azure:
    state: absent
    name: "{{ azure_name_prefix }}-{{ item.storage_account }}-{{ item.name }}"
    management_cert_path: '{{ azure_management_cert_path }}'
    subscription_id: '{{ azure_subscription_id }}'
    wait: '{{ wait|default(True) }}'
  with_items: '{{ azure_images }}'
  when: not {{skip_delete}}
