---
# Tasks to create rds instance(s)

- name: create/locate rds instance(s)
  rds:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ rds_region }}'
    command: create
    db_engine: '{{ item.db_engine }}'
    db_name: '{{ item.db_name }}'
    size: '{{ item.size }}'
    instance_type: '{{ item.instance_type }}'
    instance_name: '{{rds_name_prefix}}-{{item.name}}'
    port: '{{ rds_port }}'
    username: '{{ rds_username }}'
    password: '{{ rds_password }}'
    # security_groups: postgres
    wait: yes
    wait_timeout: 600
  with_items: rds_images
  register: rds

- debug: var=rds

# Despite using `wait` on the rds module, instances aren't accepting ssh
# connections immediately.  The following will ensure systems are ready for use
# before proceeding.
- name: wait for instances to listen on port
  wait_for:
    timeout=15
    state=started
    host={{ item.instance.endpoint }}
    port={{ item.instance.port  }}
  with_items: rds.results
  when: rds_images and rds is defined

- name: add_host
  add_host: name={{item.instance.id}}
     groups=cloud,rds
     ansible_ssh_user={{item.instance.username}}
     ansible_ssh_host={{item.instance.endpoint}}
  with_items: rds.results
  when: rds_images and rds is defined

# HACK: While sshd may be listening, it may not fully accept connections
# immediately
- name: sleep 30s
  command: sleep 30s
  when: rds_images and rds is defined and rds.changed
