# NOTE(spredzy): The ec2_remote_facts has been removed in 2.8
- name: ensure public dns name provided by aws
  ec2_remote_facts:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ ec2_region }}'
    filters:
      'tag:Name': '{{ name_to_tagged_name.values()|list }}'
      instance-state-name: ['pending', 'running']
  register: ec2_instance_vars
  until: "{{ ec2_images|length }} == {{ ec2_instance_vars.instances|length }} and {{ ec2_instance_vars.instances|selectattr('public_dns_name', 'match', '^.+$')|list|length }} == {{ ec2_instance_vars.instances|length }}"
  retries: 60
  delay: 15

- name: store public dns for all created instances
  set_fact:
    instance_id_to_public_dns: '{{ instance_id_to_public_dns | combine({item.id: item.public_dns_name}) }}'
  with_items: '{{ ec2_instance_vars.instances|default([]) }}'
