---
# Tasks to create an AMI from a running instance

- name: create ami
  ec2_ami:
    state: present
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ item.tagged_instances[0].region }}'
    instance_id: '{{ item.tagged_instances[0].id }}'
    name: '{{ec2_name_prefix}}-{{item.item.name}}'
    wait: yes
  with_items: '{{ ec2.results }}'
  register: ec2_ami
  when: ec2_images

# Display the AMI id
- debug: var=ec2_ami.results[0].image_id
