---
- name: Install EPEL
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest
  become: true

- name: Install LetsEncrypt
  yum:
    name: letsencrypt
    state: latest
    skip_broken: True
    update_cache: True
  become: true

- name: Generate certificate
  command: "letsencrypt certonly -n --standalone --agree-tos --email {{ letsencrypt_email }} -d {{ letsencrypt_domain }}"
  become: true

- name: Update cert_path
  set_fact:
    letsencrypt_cert_path: '/etc/letsencrypt/live/{{ letsencrypt_domain }}'

- name: Copy IdenTrust cert
  copy:
    src: DSTRootCAX3.pem
    dest: '{{ letsencrypt_cert_path }}/DSTRootCAX3.pem'
  become: true
