---

# Rackspace RHEL-7 images sometimes launch with an incorrect DNS configuration.
# These tasks attempt to detect that scenario, and restart the 'network'
# service to workaround the issue.
# https://mycloud.rackspace.com/cloud/849941/tickets#141112-ord-0001188

- name: detect if /etc/resolv.conf is broken
  command: grep -v "^\(#\|\s*$\)" /etc/resolv.conf
  changed_when: false
  register: is_resolv_conf_broken

- name: restart networking to regenerate /etc/resolv.conf
  service: name=network state=restarted
  when: is_resolv_conf_broken.stdout == "search 0-x86-64"
