---
# Tasks to install awx-setup package-related dependencies on EL systems

- name: include variable file
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - 'default.yml'
      paths: '../vars'

- name: install playbook dependency rpms
  yum:
    name: '{{item}}'
    state: installed
  with_items: rpm_role_dependencies
  when: ansible_pkg_mgr == 'yum'

- name: install playbook dependency debs
  apt:
    pkg: '{{item}}'
    state: latest
    update_cache: yes
  with_items: deb_role_dependencies
  when: ansible_pkg_mgr == 'apt'

- name: include rhui tasks
  include: rhui.yml
  when: ansible_distribution == 'RedHat'

- name: include rhsm tasks
  include: rhsm.yml
  when: ansible_distribution == 'RedHat'

- name: include epel tasks
  include: epel.yml
  when: ansible_os_family == 'RedHat' and ansible_install_method in ['stable', 'testing', 'nightly']

# install ansible nightly rpm repo (optional)

- name: install ansible nightly yum repository
  template:
    src: files/ansible_yum.repo.j2
    dest: /etc/yum.repos.d/ansible.repo
  register: yum_repo
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly'

- name: yum clean cached ansible repository information
  command: yum clean all --disablerepo=* --enablerepo=ansible-nightly
  when: yum_repo is defined and yum_repo.changed

# install ansible nightly rpm repo (optional)

- name: install ansible nightly apt repository
  template:
    src: files/ansible_apt.repo.j2
    dest: /etc/apt/sources.list.d/ansible_repo.list
  when: ansible_pkg_mgr == 'apt' and ansible_install_method == 'nightly'

# install ansible ppa

- name: install ansible stable apt repository
  apt_repository:
    repo: '{{ansible_ppa}}'
    state: present
  when: ansible_pkg_mgr == 'apt' and ansible_ppa is defined

# install ansible

- name: install ansible rpm (stable)
  yum:
    name: ansible
    state: latest
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'stable'

- name: install ansible rpm (testing)
  yum:
    name: ansible
    enablerepo: '*-testing'
    state: latest
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'testing'

- name: install ansible rpm (nightly)
  yum:
    name: ansible
    enablerepo: ansible-nightly
    state: latest
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly'

- name: install ansible deb
  apt:
    name: ansible
    state: latest
    update_cache: yes
    force: yes
  when: ansible_pkg_mgr == 'apt' and ansible_install_method in ['stable', 'testing', 'nightly']

- name: install pip rpm
  yum:
    name: python-pip
    state: installed
  when: ansible_install_method == 'pip' and ansible_pkg_mgr == 'yum'

- name: install pip deb
  apt:
    name: python-pip
    state: installed
  when: ansible_install_method == 'pip' and ansible_pkg_mgr == 'apt'

- name: install ansible pip
  pip:
    name: '{{ansible_pip}}'
    state: latest
  when: ansible_install_method == 'pip'

- name: verify that ansible was installed
  command: ansible --version
  changed_when: false
  when: ansible_install_method != None
