---
# Tasks to install awx-setup package-related dependencies on EL systems

- name: update yum
  yum:
    name: yum
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: update apt
  apt:
    pkg: apt
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: include variable file
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - 'default.yml'
      paths: '../vars'

- name: install playbook dependency debs
  apt:
    pkg: '{{item}}'
    state: latest
  with_items: '{{ deb_role_dependencies }}'
  when: ansible_pkg_mgr == 'apt'

- name: include rhui tasks
  include: rhui.yml
  when: ansible_distribution == 'RedHat'

- name: include rhsm tasks
  include: rhsm.yml
  when: ansible_distribution == 'RedHat'

- name: include epel tasks
  include: epel.yml
  when: ansible_os_family == 'RedHat' and ansible_install_method in ['stable', 'testing', 'nightly', 'pip']

- name: install playbook dependency rpms
  yum:
    name: '{{item}}'
    state: installed
  with_items: '{{ rpm_role_dependencies }}'
  when: ansible_pkg_mgr == 'yum'

# https://bugzilla.redhat.com/show_bug.cgi?id=1405175
- name: update selinux-policy
  yum:
    name: selinux-policy
    state: latest
  when: ansible_pkg_mgr == 'yum'

# install ansible nightly yum repo (optional)

- name: install ansible nightly yum repository
  template:
    src: files/ansible_yum.repo.j2
    dest: /etc/yum.repos.d/ansible.repo
  register: yum_repo
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly'

- name: yum clean cached ansible repository information
  command: yum clean all --disablerepo=* --enablerepo=ansible-nightly
  when: yum_repo is defined and yum_repo.changed

# install ansible nightly apt repo (optional)

- name: install ansible nightly apt repository
  template:
    src: files/ansible_apt.repo.j2
    dest: /etc/apt/sources.list.d/ansible_repo.list
  when: ansible_pkg_mgr == 'apt' and ansible_install_method == 'nightly'

# enable epel-testing repo (optional)

- name: Enable epel-testing repo (testing)
  command: yum-config-manager --enable epel-testing
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'testing'

# enable ansible-nightly repo (optional)

- name: Enable ansible repo (nightly)
  command: yum-config-manager --enable ansible-nightly
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly'

# install ansible ppa

- name: install ansible stable apt repository
  apt_repository:
    repo: '{{ansible_ppa}}'
    state: present
    mode: '0644'
  when: ansible_pkg_mgr == 'apt' and ansible_ppa is defined and ansible_install_method != 'nightly'

# install ansible

- name: install ansible rpm (stable/testing)
  yum:
    name: '{{ ansible_package_name }}'
    state: latest
  when: ansible_pkg_mgr == 'yum' and ansible_install_method in ['stable', 'testing']

- name: gather ansible nightly dependencies
  command: yum deplist --disablerepo=* --enablerepo=ansible-nightly ansible
  register: nightly_dep_candidates
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly'

- name: filter nightly ansible dependency candidates
  set_fact:
    nightly_ansible_dependencies: |
      {{ nightly_dep_candidates.stdout_lines|map("regex_search", ".*dependency.*")
      |select("string")|map("regex_replace", "  dependency: ", "")
      |map("regex_search", "^[a-zA-Z0-9\-]+$")|select("string")|list }}
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly' and nightly_dep_candidates is defined

- name: install ansible nightly dependencies
  yum:
    name: '{{ item }}'
    state: latest
  with_items: '{{ nightly_ansible_dependencies }}'
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly' and nightly_ansible_dependencies is defined

- name: install ansible rpm (nightly)
  yum:
    name: '{{ ansible_package_name }}'
    state: latest
    disablerepo: '*'
    enablerepo: ansible-nightly
  when: ansible_pkg_mgr == 'yum' and ansible_install_method == 'nightly'

- name: install ansible deb
  apt:
    name: '{{ ansible_package_name }}'
    state: present
    update_cache: yes
    force: yes
  when: ansible_pkg_mgr == 'apt' and ansible_install_method in ['stable', 'testing', 'nightly']

- name: install pip rpm
  yum:
    name: python-pip
    state: installed
  when: ansible_install_method == 'pip' and ansible_pkg_mgr == 'yum'

- name: install pip deb
  apt:
    name: python-pip
    state: latest
  when: ansible_install_method == 'pip' and ansible_pkg_mgr == 'apt' and ansible_distribution_major_version != '12'

# The version of pip on ubuntu-12.04 is older than ancient ... the following
# dark arts will ensure a working version is installed.
- name: install pip deb (12.04 only)
  shell: "curl https://bootstrap.pypa.io/get-pip.py | python -"
  register: result
  changed_when: '"Successfully installed" in result.stdout'
  when: ansible_install_method == 'pip' and ansible_pkg_mgr == 'apt' and ansible_distribution_major_version == '12'

- name: install ansible pip
  pip:
    name: '{{ ansible_package_name }}'
    state: latest
  when: ansible_install_method == 'pip'

- name: verify that ansible was installed
  command: ansible --version
  changed_when: false
  when: ansible_install_method not in ['none', None]
