---
# If the desired image exists, the value of `skip` determines
# whether to delete the existing image
skip: true

# azure_name_prefix: '{{ instance_name_prefix }}'
azure_name_prefix: 'jenkins'
azure_location: 'East US'
azure_endpoints: '22,80,443,8080'
azure_management_cert_path: ''
azure_ssh_user: ''
azure_ssh_cert_path: ''
azure_storage_account: ''
azure_subscription_id: ''

# Default list of images
azure_images: []
