---
# Tasks to install awx-setup package-related dependencies on EL systems

# install deps

- name: install debian dependencies
  apt: pkg=python-pycurl state=latest
  when: ansible_pkg_mgr == 'apt'

# install ansible ppa

- name: enable ppa:rquillo/ansible
  apt_repository: repo='ppa:rquillo/ansible' state=present
  when: ansible_pkg_mgr == 'apt'

# install ansible nightly rpm repo (optional)

- name: install nightly ansible repository
  template: src=files/ansible_apt.repo.j2 dest=/etc/apt/sources.list.d/ansible_repo.list
  when: ansible_pkg_mgr == 'apt' and ansible_repo_url is defined

# install ansible

- name: install ansible
  apt: pkg=ansible state=latest update_cache=yes force=yes
  when: ansible_pkg_mgr == 'apt'
