---
# Tasks to install awx-setup package-related dependencies on EL systems

# install deps

- name: install debian dependencies
  apt: pkg={{item}} state=latest
  when: ansible_pkg_mgr == 'apt'
  with_items:
    - python-pycurl
    - python2.7-dev # needed for pip task below (remove later)
    - python-pip    # needed for pip task below (remove later)

# install ansible ppa

- name: enable ppa:rquillo/ansible
  apt_repository: repo='ppa:rquillo/ansible' state=present
  when: ansible_pkg_mgr == 'apt'

# install ansible nightly rpm repo (optional)

- name: install nightly ansible repository
  template: src=files/ansible_apt.repo.j2 dest=/etc/apt/sources.list.d/ansible_repo.list
  when: ansible_pkg_mgr == 'apt' and ansible_repo_url is defined

# install ansible

- name: install ansible deb
  apt: pkg=ansible state=latest update_cache=yes force=yes
  when: ansible_pkg_mgr == 'apt' and ansible_distribution_release != 'trusty'

# TODO: remove the following when 'trusty' packages are available
- name: install ansible pip
  pip: name=ansible state=latest
  when: ansible_pkg_mgr == 'apt' and ansible_distribution_release == 'trusty'
