---
# AWS variables
aws_url: 'https://ec2.amazonaws.com'
aws_access_key: ''
aws_secret_key: ''
ec2_region: 'us-east-1'
ec2_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
ec2_name_prefix: '{{ instance_name_prefix }}'
max_preserving_number: '1000'
max_preserving_time: '604800' # seconds of 7 days
