---

additionalProperties: false
properties:
  AUTH_LDAP_SERVER_URI: {type: string}
  AUTH_LDAP_BIND_DN: {type: string}
  AUTH_LDAP_BIND_PASSWORD: {type: string}
  AUTH_LDAP_START_TLS: {type: boolean}
  AUTH_LDAP_CONNECTION_OPTIONS:
    additionalProperties:
    properties:
      OPT_REFERRALS:
    required: [OPT_REFERRALS]
    type: object
  AUTH_LDAP_USER_SEARCH:
  AUTH_LDAP_USER_DN_TEMPLATE: {type: string}
  AUTH_LDAP_USER_ATTR_MAP: {type: object}
  AUTH_LDAP_GROUP_SEARCH:
  AUTH_LDAP_GROUP_TYPE:
  AUTH_LDAP_REQUIRE_GROUP: {type: string}
  AUTH_LDAP_DENY_GROUP: {type: string}
  AUTH_LDAP_USER_FLAGS_BY_GROUP: {type: object}
  AUTH_LDAP_ORGANIZATION_MAP: {type: object}
  AUTH_LDAP_TEAM_MAP: {type: object}
required: []
type: object
'''
{
    "AUTH_LDAP_SERVER_URI": "None",
    "AUTH_LDAP_BIND_DN": "",
    "AUTH_LDAP_BIND_PASSWORD": "",
    "AUTH_LDAP_START_TLS": false,
    "AUTH_LDAP_CONNECTION_OPTIONS": {
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_USER_SEARCH": [],
    "AUTH_LDAP_USER_DN_TEMPLATE": "",
    "AUTH_LDAP_USER_ATTR_MAP": {},
    "AUTH_LDAP_GROUP_SEARCH": [],
    "AUTH_LDAP_GROUP_TYPE": null,
    "AUTH_LDAP_REQUIRE_GROUP": "",
    "AUTH_LDAP_DENY_GROUP": "",
    "AUTH_LDAP_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_ORGANIZATION_MAP": {},
    "AUTH_LDAP_TEAM_MAP": {}
}
'''
