---

additionalProperties: false
properties:
  SOCIAL_AUTH_SAML_CALLBACK_URL
  SOCIAL_AUTH_SAML_METADATA_URL
  SOCIAL_AUTH_SAML_SP_ENTITY_ID: {type: string}
  SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: {type: string}
  SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: {type: string}
  SOCIAL_AUTH_SAML_ORG_INFO: {type: object}
  SOCIAL_AUTH_SAML_TECHNICAL_CONTACT: {type: object}
  SOCIAL_AUTH_SAML_SUPPORT_CONTACT: {type: object}
  SOCIAL_AUTH_SAML_ENABLED_IDPS: {type: object}
  SOCIAL_AUTH_SAML_ORGANIZATION_MAP
  SOCIAL_AUTH_SAML_TEAM_MAP
required: [SOCIAL_AUTH_SAML_CALLBACK_URL, SOCIAL_AUTH_SAML_METADATA_URL, SOCIAL_AUTH_SAML_SP_ENTITY_ID, SOCIAL_AUTH_SAML_SP_PUBLIC_CERT, SOCIAL_AUTH_SAML_SP_PRIVATE_KEY, SOCIAL_AUTH_SAML_ORG_INFO, SOCIAL_AUTH_SAML_TECHNICAL_CONTACT, SOCIAL_AUTH_SAML_SUPPORT_CONTACT, SOCIAL_AUTH_SAML_ENABLED_IDPS, SOCIAL_AUTH_SAML_ORGANIZATION_MAP, SOCIAL_AUTH_SAML_TEAM_MAP]
type: object

'''
{
    "SOCIAL_AUTH_SAML_CALLBACK_URL": "https://towerhost/sso/complete/saml/",
    "SOCIAL_AUTH_SAML_METADATA_URL": "https://towerhost/sso/metadata/saml/",
    "SOCIAL_AUTH_SAML_SP_ENTITY_ID": "",
    "SOCIAL_AUTH_SAML_SP_PUBLIC_CERT": "",
    "SOCIAL_AUTH_SAML_SP_PRIVATE_KEY": "",
    "SOCIAL_AUTH_SAML_ORG_INFO": {},
    "SOCIAL_AUTH_SAML_TECHNICAL_CONTACT": {},
    "SOCIAL_AUTH_SAML_SUPPORT_CONTACT": {},
    "SOCIAL_AUTH_SAML_ENABLED_IDPS": {},
    "SOCIAL_AUTH_SAML_ORGANIZATION_MAP": null,
    "SOCIAL_AUTH_SAML_TEAM_MAP": null
}
'''
