---
$schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/all/'
type: object
additionalProperties: false
properties:
  AD_HOC_COMMANDS:
    type: array
    minItems: 0
    uniqueItems: true
    items:
      type: string  
  AWX_PROOT_ENABLED: {type: boolean}
  AWX_PROOT_BASE_PATH: {type: string}
  AWX_PROOT_HIDE_PATHS:
    type: array
    minItems: 0
    uniqueItems: true
  AWX_PROOT_SHOW_PATHS:
    type: array
    minItems: 0
    uniqueItems: true
  STDOUT_MAX_BYTES_DISPLAY: {type: number, minimum: 0}
  SCHEDULE_MAX_JOBS: {type: number, minimum: 1}
  AWX_ANSIBLE_CALLBACK_PLUGINS:
    type: array
    minItems: 0
    uniqueItems: true
required: [AD_HOC_COMMANDS, AWX_PROOT_ENABLED, AWX_PROOT_BASE_PATH, AWX_PROOT_HIDE_PATHS, AWX_PROOT_SHOW_PATHS, STDOUT_MAX_BYTES_DISPLAY, SCHEDULE_MAX_JOBS, AWX_ANSIBLE_CALLBACK_PLUGINS]
