---
$schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/google-oauth2/'
type: object
additionalProperties: false
properties:
  SOCIAL_AUTH_GOOGLE_OAUTH2_CALLBACK_URL: {format: uri, type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: {type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: {type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS:
    type: array
    minItems: 0
    uniqueItems: true
    items:
      type: string
  SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS: {type: object}
  SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP: {type: 'null'}
  SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP: {type: 'null'}
required: [SOCIAL_AUTH_GOOGLE_OAUTH2_CALLBACK_URL, SOCIAL_AUTH_GOOGLE_OAUTH2_KEY, SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET, SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS, SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS, SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP, SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP]
