---
$schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/github-org/'
type: object
additionalProperties: false
properties:
  SOCIAL_AUTH_GOOGLE_OAUTH2_CALLBACK_URL:
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: {type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: {type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS:
  SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS: {type: object}
  SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP
  SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP
required: [SOCIAL_AUTH_GOOGLE_OAUTH2_CALLBACK_URL, SOCIAL_AUTH_GOOGLE_OAUTH2_KEY, SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET, SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS, SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS, SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP, SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP]

'''
{
    "SOCIAL_AUTH_GOOGLE_OAUTH2_CALLBACK_URL": "https://towerhost/sso/complete/google-oauth2/",
    "SOCIAL_AUTH_GOOGLE_OAUTH2_KEY": "",
    "SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET": "",
    "SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS": [],
    "SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS": {},
    "SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP": null,
    "SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP": null
}
'''
