---
$schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/all/'
type: object
additionalProperties: false
properties:
  ACTIVITY_STREAM_ENABLED: {type: boolean}
  ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: {type: boolean}
  ORG_ADMINS_CAN_SEE_ALL_USERS: {type: boolean}
  TOWER_ADMIN_ALERTS: {type: boolean}
  TOWER_URL_BASE: {type: string}
  REMOTE_HOST_HEADERS:
  LICENSE:
  AD_HOC_COMMANDS:
  AWX_PROOT_ENABLED: {type: boolean}
  AWX_PROOT_BASE_PATH: {type: string}
  AWX_PROOT_HIDE_PATHS:
  AWX_PROOT_SHOW_PATHS:
  STDOUT_MAX_BYTES_DISPLAY: {type: number, mini/mum: 0}
  SCHEDULE_MAX_JOBS: {type: number, minimum: 1}
  AWX_ANSIBLE_CALLBACK_PLUGINS:
  AUTH_TOKEN_EXPIRATION:
  AUTH_TOKEN_PER_USER: 
  AUTH_BASIC_ENABLED: {type: boolean}
  PENDO_TRACKING_STATE: {type: string}
  AUTHENTICATION_BACKENDS
  SOCIAL_AUTH_ORGANIZATION_MAP: {type: object}
  SOCIAL_AUTH_TEAM_MAP: {type: object}
  SOCIAL_AUTH_USER_FIELDS:
  AUTH_LDAP_SERVER_URI: {type: string}
  AUTH_LDAP_BIND_DN: {type: string}
  AUTH_LDAP_BIND_PASSWORD: {type: string}
  AUTH_LDAP_START_TLS: {type: boolean}
  AUTH_LDAP_CONNECTION_OPTIONS
  AUTH_LDAP_USER_SEARCH: 
  AUTH_LDAP_USER_DN_TEMPLATE: {type: string}
  AUTH_LDAP_USER_ATTR_MAP: {type: object}
  AUTH_LDAP_GROUP_SEARCH
  AUTH_LDAP_GROUP_TYPE
  AUTH_LDAP_REQUIRE_GROUP: {type: string}
  AUTH_LDAP_DENY_GROUP: {type: string}
  AUTH_LDAP_USER_FLAGS_BY_GROUP: {type: object}
  AUTH_LDAP_ORGANIZATION_MAP: {type: object}
  AUTH_LDAP_TEAM_MAP: {type: object}
  RADIUS_SERVER: {type: string}
  RADIUS_PORT
  RADIUS_SECRET: {type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_CALLBACK_URL: {format: uri, type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: {type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: {type: string}
  SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS
  SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS: {type: object}
  SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP
  SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP
  SOCIAL_AUTH_GITHUB_CALLBACK_URL: {format: uri, type: string}
  SOCIAL_AUTH_GITHUB_KEY: {type: string}
  SOCIAL_AUTH_GITHUB_SECRET: {type: string}
  SOCIAL_AUTH_GITHUB_ORGANIZATION_MAP
  SOCIAL_AUTH_GITHUB_TEAM_MAP
  SOCIAL_AUTH_GITHUB_ORG_CALLBACK_URL: {format: uri, type: string}
  SOCIAL_AUTH_GITHUB_ORG_KEY: {type: string}
  SOCIAL_AUTH_GITHUB_ORG_SECRET: {type: string}
  SOCIAL_AUTH_GITHUB_ORG_NAME: {type: string}
  SOCIAL_AUTH_GITHUB_ORG_ORGANIZATION_MAP:
  SOCIAL_AUTH_GITHUB_ORG_TEAM_MAP
  SOCIAL_AUTH_GITHUB_TEAM_CALLBACK_URL: {format: uri, type: string}
  SOCIAL_AUTH_GITHUB_TEAM_KEY: {type: string}
  SOCIAL_AUTH_GITHUB_TEAM_SECRET: {type: string}
  SOCIAL_AUTH_GITHUB_TEAM_ID: {type: string}
  SOCIAL_AUTH_GITHUB_TEAM_ORGANIZATION_MAP
  SOCIAL_AUTH_SAML_CALLBACK_URL: {format: uri, type: string}
  SOCIAL_AUTH_SAML_METADATA_URL: {format: uri, type: string}
  SOCIAL_AUTH_SAML_SP_ENTITY_ID: {type: string}
  SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: {type: string}
  SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: {type: string}
  SOCIAL_AUTH_SAML_ORG_INFO: {type: object}
  SOCIAL_AUTH_SAML_TECHNICAL_CONTACT: {type: object}
  SOCIAL_AUTH_SAML_SUPPORT_CONTACT: {type: object}
  SOCIAL_AUTH_SAML_ENABLED_IDPS: {type: object}
  SOCIAL_AUTH_SAML_ORGANIZATION_MAP
  SOCIAL_AUTH_SAML_TEAM_MAP
required: [ACTIVITY_STREAM_ENABLED]
