---
$schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/github/'
type: object
additionalProperties: false
properties:
  SOCIAL_AUTH_GITHUB_CALLBACK_URL:
  SOCIAL_AUTH_GITHUB_KEY: {type: string}
  SOCIAL_AUTH_GITHUB_SECRET: {type: string}
  SOCIAL_AUTH_GITHUB_ORGANIZATION_MAP:
  SOCIAL_AUTH_GITHUB_TEAM_MAP:
required: [SOCIAL_AUTH_GITHUB_CALLBACK_URL, SOCIAL_AUTH_GITHUB_KEY, SOCIAL_AUTH_GITHUB_SECRET, SOCIAL_AUTH_GITHUB_ORGANIZATION_MAP, SOCIAL_AUTH_GITHUB_TEAM_MAP]

'''
{
    "SOCIAL_AUTH_GITHUB_CALLBACK_URL": "https://towerhost/sso/complete/github/",
    "SOCIAL_AUTH_GITHUB_KEY": "",
    "SOCIAL_AUTH_GITHUB_SECRET": "",
    "SOCIAL_AUTH_GITHUB_ORGANIZATION_MAP": null,
    "SOCIAL_AUTH_GITHUB_TEAM_MAP": null
}
'''
