---
$schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/github-org/'
type: object
additionalProperties: false
properties:
  SOCIAL_AUTH_GITHUB_TEAM_CALLBACK_URL:
  SOCIAL_AUTH_GITHUB_TEAM_KEY: {type: string}
  SOCIAL_AUTH_GITHUB_TEAM_SECRET: {type: string}
  SOCIAL_AUTH_GITHUB_TEAM_ID: {type: string}
  SOCIAL_AUTH_GITHUB_TEAM_ORGANIZATION_MAP
  SOCIAL_AUTH_GITHUB_TEAM_TEAM_MAP
required: [SOCIAL_AUTH_GITHUB_TEAM_CALLBACK_URL, SOCIAL_AUTH_GITHUB_TEAM_KEY, SOCIAL_AUTH_GITHUB_TEAM_SECRET, SOCIAL_AUTH_GITHUB_TEAM_ID, SOCIAL_AUTH_GITHUB_TEAM_ORGANIZATION_MAP, SOCIAL_AUTH_GITHUB_TEAM_TEAM_MAP]

'''
{
    "SOCIAL_AUTH_GITHUB_TEAM_CALLBACK_URL": "https://towerhost/sso/complete/github-team/",
    "SOCIAL_AUTH_GITHUB_TEAM_KEY": "",
    "SOCIAL_AUTH_GITHUB_TEAM_SECRET": "",
    "SOCIAL_AUTH_GITHUB_TEAM_ID": "",
    "SOCIAL_AUTH_GITHUB_TEAM_ORGANIZATION_MAP": null,
    "SOCIAL_AUTH_GITHUB_TEAM_TEAM_MAP": null
}
'''
