---
schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/radius/'
additionalProperties: false
properties:
  RADIUS_SERVER: {type: string}
  RADIUS_PORT: {minimum: 1, type: number}
  RADIUS_SECRET: {type: string}
required: [RADIUS_SERVER, RADIUS_PORT, RADIUS_SECRET]
type: object
