---

additionalProperties: false
properties:
  ACTIVITY_STREAM_ENABLED: {type: boolean}
  ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: {type: boolean}
  ORG_ADMINS_CAN_SEE_ALL_USERS: {type: boolean}
  TOWER_ADMIN_ALERTS: {type: boolean}
  TOWER_URL_BASE:
  REMOTE_HOST_HEADERS:
  LICENSE:
    additionalProperties: false
    properties:
     
    required: []
    type: object
required: [ACTIVITY_STREAM_ENABLED, ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC, ORG_ADMINS_CAN_SEE_ALL_USERS, TOWER_ADMIN_ALERTS, TOWER_URL_BASE, REMOTE_HOST_HEADERS, LICENSE]
type: object  

'''
{
    "ACTIVITY_STREAM_ENABLED": true,
    "ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC": false,
    "ORG_ADMINS_CAN_SEE_ALL_USERS": true,
    "TOWER_ADMIN_ALERTS": true,
    "TOWER_URL_BASE": "https://towerhost",
    "REMOTE_HOST_HEADERS": [
        "REMOTE_ADDR",
        "REMOTE_HOST"
    ],
    "LICENSE": {
        "subscription_name": "Enterprise Tower up to 100000 Nodes",
        "features": {},
        "instance_count": 100000,
        "trial": false,
        "contact_email": "gross@weiner.com",
        "company_name": "Dr. James Grossweiner",
        "license_type": "enterprise",
        "contact_name": "Dr. James Grossweiner",
        "license_date": 2524608000,
        "license_key": "cf2da1fdbc196c3f9a354d871cdad572dcd2e309a1e49616d8d9c600a9b7fc91"
    }
}
'''
