---
$schema: http://json-schema.org/draft-04/schema#
id: '/api/v1/settings/authentication/'
type: object
additionalProperties: false
properties:
  AUTH_TOKEN_EXPIRATION: {type: number, minimum: 60}
  AUTH_TOKEN_PER_USER: {type: number, minimum: -1}
  AUTH_BASIC_ENABLED: {type: boolean}
  AUTHENTICATION_BACKENDS:
    type: array
    minItems: 0
    uniqueItems: true
    items:
      type: string
  SOCIAL_AUTH_ORGANIZATION_MAP: {type: object}
  SOCIAL_AUTH_TEAM_MAP: {type: object}
  SOCIAL_AUTH_USER_FIELDS: {type: 'null'}
required: [AUTH_TOKEN_EXPIRATION, AUTH_TOKEN_PER_USER, AUTH_BASIC_ENABLED, AUTHENTICATION_BACKENDS, SOCIAL_AUTH_ORGANIZATION_MAP, SOCIAL_AUTH_TEAM_MAP, SOCIAL_AUTH_USER_FIELDS]
