---
# If the desired image exists, the value of `skip_delete` determines
# whether to use the existing image, or to delete it before proceeding
skip_delete: false

# AWS variables
aws_url: 'https://ec2.amazonaws.com'
aws_access_key: ''
aws_secret_key: ''
win_ec2_region: 'us-east-1'
win_ec2_instance_type: 'm3.medium'
win_ec2_security_group: 'Ansible WinRM'
win_ec2_key_name: 'ansible-winrm'
win_ec2_name_prefix: '{{ win_instance_name_prefix }}'
# win_ec2_images are defined in group_vars/all since they are needed by multiple roles
# win_ec2_images: []
