project:
  additionalProperties: false
  properties:
    created: {format: date-time, type: string}
    credential:
      type: [number, 'null']
    description: {type: string}
    has_schedules: {type: boolean}
    id: {minimum: 1, type: number}
    last_job_failed: {type: boolean}
    last_job_run:
      format: date-time
      type: [string, 'null']
    last_update_failed: {type: boolean}
    last_updated:
      format: date-time
      type: [string, 'null']
    local_path: {format: uri, type: string}
    modified: {format: date-time, type: string}
    name: {type: string}
    next_job_run:
      format: date-time
      type: [string, 'null']
    organization: {$ref: '#/definitions/id_or_null'}
    related:
      additionalProperties: false
      properties:
        access_list: {format: uri, type: string}
        activity_stream: {format: uri, type: string}
        created_by: {format: uri, type: string}
        credential: {format: uri, type: string}
        current_job: {format: uri, type: string}
        current_update: {format: uri, type: string}
        last_job: {format: uri, type: string}
        last_update: {format: uri, type: string}
        modified_by: {format: uri, type: string}
        next_schedule: {format: uri, type: string}
        notification_templates_any: {format: uri, type: string}
        notification_templates_error: {format: uri, type: string}
        notification_templates_success: {format: uri, type: string}
        organization: {format: uri, type: string}
        playbooks: {format: uri, type: string}
        project_updates: {format: uri, type: string}
        object_roles: {format: uri, type: string}
        schedules: {format: uri, type: string}
        teams: {format: uri, type: string}
        update: {format: uri, type: string}
      required: [created_by, project_updates, playbooks, update, teams,
        activity_stream, notification_templates_any, notification_templates_error,
        notification_templates_success, access_list, object_roles]
      type: object
    scm_branch: {type: string}
    scm_clean: {type: boolean}
    scm_delete_on_next_update: {type: boolean}
    scm_delete_on_update: {type: boolean}
    scm_revision: {type: string}
    scm_type:
      type: [string, 'null']
    scm_update_cache_timeout: {minimum: 0, type: integer}
    scm_update_on_launch: {type: boolean}
    scm_url: {type: string}
    status: {$ref: '#/definitions/enum_project_status'}
    summary_fields:
      additional_properties: false
      properties:
        last_job: {$ref: '#/definitions/summary_fields_job'}
        last_update: {$ref: '#/definitions/summary_fields_job'}
        organization: {$ref: '#/definitions/summary_fields_organization'}
        created_by: {$ref: '#/definitions/summary_fields_user'}
        object_roles:
          additionalProperties: false
          properties:
            admin_role: {$ref: '#/definitions/summary_fields_role'}
            update_role: {$ref: '#/definitions/summary_fields_role'}
            use_role: {$ref: '#/definitions/summary_fields_role'}
            read_role: {$ref: '#/definitions/summary_fields_role'}
          required: [admin_role, update_role, use_role, read_role]
          type: object
      required: [object_roles]
      type: object
    timeout: {minimum: 0, type: integer}
    type: {pattern: ^project$, type: string}
    url: {format: uri, type: string}
  required: [id, name, url, created, modified, last_job_run, description, last_job_failed,
    status, summary_fields, local_path, scm_type, scm_update_cache_timeout, scm_url,
    scm_branch, scm_clean, scm_delete_on_update, scm_delete_on_next_update, scm_update_on_launch,
    credential, type, has_schedules, next_job_run, scm_revision, timeout]
  type: object
