---
# This playbook deploys the AWX application (database, web and worker) to a
# multiple platforms across multiple cloud providers.

#
# Create remote hosts
#
- hosts: local
  roles:
    - { role: create_rax }
    - { role: create_ec2 }
    - { role: save_inventory }

#
# Dynamically create host groups based on distribution
#
- hosts: all
  tasks:
   - name: group hosts by distribution
     action: group_by key={{ansible_distribution}}

#
# Install awx_setup on RHEL-like systems
#
- hosts: CentOS:RedHat:&all_instances
  user: root
  roles:
    - { role: packages_el }
    - { role: auth_keys }
    - { role: awx_setup }

#
# Install awx_setup on Ubuntu systems
#
- hosts: Ubuntu:&all_instances
  user: root
  roles:
    - { role: packages_ubuntu }
    - { role: auth_keys }
    - { role: awx_setup }
