---
# Tasks to delete win ec2 instances

- name: delete existing win ec2 instance(s)
  ec2:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ win_ec2_region }}'
    instance_type: '{{ win_ec2_instance_type }}'
    instance_tags:
        Name: '{{win_ec2_name_prefix}}-{{item.name}}'
    group: '{{ win_ec2_security_group }}'
    key_name: '{{ win_ec2_key_name }}'
    image: '{{ item.id }}'
    exact_count: 0
    count_tag:
        Name: '{{win_ec2_name_prefix}}-{{item.name}}'
    wait: yes
  with_items: win_ec2_images
  when: not {{skip_delete}}
