---
# This playbook installs ansible to multiple platforms across multiple cloud
# providers.

#
# Create remote hosts
#
- hosts: local
  roles:
    - { role: deploy_cloud }

#
# Dynamically create host groups based on distribution
#
- hosts: all
  tasks:
   - name: group hosts by distribution
     action: group_by key={{ansible_distribution}}

#
# Install ansible
#
- hosts: '!local'
  sudo: yes
  roles:
    - { role: ansible_install }
