---
- hosts: all
  vars:
    venv_base: /var/lib/awx/venv
    venv_folder_name: custom-venv
    remote_python: python
  tasks:
    - block:
        - block:
            - name: Install needed packages
              package:
                name:
                  - python-virtualenv
                  - gcc

            - name: Install epel to provide python3-devel if on rhel7 (required for some packages installed by pip)
              package:
                name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
              when: remote_python == 'python36'

            - name: Install python36 and python36-devel if on rhel7 and want python3
              package:
                name:
                  - python36
                  - python36-devel
              when: remote_python == 'python36'

            - set_fact:
                _remote_python: python3.6
              when: remote_python == 'python36'

          when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

        - block:
            - name: Install needed packages
              package:
                name:
                  - python3-virtualenv
                  - python2-devel
                  - gcc

            - name: Ensure /usr/bin/python link is maintained
              file:
                src: /usr/bin/python3
                dest: /usr/bin/python
                state: link

            - set_fact:
                _remote_python: python3
              when: remote_python == 'python36'

            - set_fact:
                _remote_python: /usr/libexec/platform-python
              when: remote_python == 'python'

          when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

        - name: Check if the virtualenv already exists
          stat:
            path: "{{ venv_base }}/{{ venv_folder_name }}"
          register: existing_folder

        - name: Create custom virtualenv
          command: "virtualenv -p {{ _remote_python | default(remote_python) }} --system-site-packages {{ venv_base }}/{{ venv_folder_name }}"
          when: not existing_folder.stat.exists and not (ansible_pkg_mgr == 'apt' and remote_python == 'python36')

        - name: Print packages to install
          debug:
            msg: "Packages to install in venv: {{ venv_packages|default('psutil (default packages)') }}"

        - name: Pip install required packages
          command: "{{ venv_base }}/{{ venv_folder_name }}/bin/pip install -I -U {{ venv_packages|default('psutil') }}"
          when:
            - venv_packages != ''
            - not existing_folder.stat.exists
      become: "{{ use_become | default('true') | bool}}"
      when: not remove_virtualenv | default(false) | bool

    - name: Remove custom virtualenv
      file:
        path: "{{ venv_base }}/{{ venv_folder_name }}"
        state: absent
      become: "{{ use_become | default('true') | bool}}"
      when: remove_virtualenv | default(false) | bool

    - name: Remove epel if we put it in place
      yum:
        name: epel-release
        state: absent
      become: "{{ use_become | default('true') | bool}}"
      when: (remove_virtualenv | default(false)) and (ansible_pkg_mgr == 'yum' and ansible_distribution_major_version == '7' and remote_python == 'python36')

    - name: Remove python36 if we put it in place
      yum:
        name: ['python36-devel', 'python36']
        state: absent
      become: "{{ use_become | default('true') | bool}}"
      when: (remove_virtualenv | default(false)) and (ansible_pkg_mgr == 'yum' and ansible_distribution_major_version == '7' and remote_python == 'python36')
