---
#
# To run playbook:
#
# ansible-playbook -i playbooks/inventory playbooks/ctint-migrations.yml -e @playbooks/tower-vars.yml -e @playbooks/images-ec2.yml
#
# Note: we use tower-vars.yml to set the variables that we need the setup playbook to install completely. As an example, setting the
# following:
#   minimum_var_space: 0
#   gpgcheck: 0
#   pendo_state: 'off'
#

- name: 'Create AWS instances'
  hosts: local
  roles:
    - role: create_ec2
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.ctint'

- name: 'Install Tower'
  hosts: 'tower,primary'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: awx_setup
  vars:
    aw_repo_url: 'http://jenkins.testing.ansible.com/ansible-tower_nightlies_v16jn0ez3t7k07/release_3.0.3'

- name: 'Populate Tower instance with settings'
  hosts: 'tower,primary'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: ctint_migrations

- name: 'Install Tower'
  hosts: 'tower,primary'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: awx_setup
  vars:
    aw_repo_url: 'http://jenkins.testing.ansible.com/ansible-tower_nightlies_v16jn0ez3t7k07/release_3.1.0'
    awx_upgrade: true
