---
- name: 'Create AWS instances'
  hosts: local
  roles:
    - role: create_ec2
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.ctit'

- name: 'Install Tower'
  hosts: 'tower,primary'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: awx_setup
  vars:
    aw_repo_url: 'http://jenkins.testing.ansible.com/ansible-tower_nightlies_RTYUIOPOIUYTYU/release_3.0.3'

- name: 'Populate Tower instance with settings'
  hosts: 'tower,primary'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: ctit_migrations

- name: 'Install Tower'
  hosts: 'tower,primary'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: awx_setup
  vars:
    aw_repo_url: 'http://jenkins.testing.ansible.com/ansible-tower_nightlies_RTYUIOPOIUYTYU/release_3.1.0'
    awx_upgrade: true
