---
- name: Deploy cloud hosts
  hosts: local
  tasks:
    - include_role:
        name: create_ec2

    - include_role:
        name: save_inventory
      vars:
        my_inventory_file: '{{inventory_dir}}/inventory.cluster'

- name: Retrieve Public IPs of all instances
  hosts: all
  tasks:
    - ipify_facts:

- name: Enable FIPS for isolated nodes
  hosts: 'tower:isolated_group*:instance_group*'
  tasks:
    - name: Run FIPS Role
      include_role:
        name: fips
      when: "'7.5' in ansible_distribution_version and fips_enabled | default(true) | bool"

- name: 'Add authorized keys on non-installer instances'
  hosts: 'tower:instance_group_*:database:haproxy:managed_hosts:!cluster_installer'
  roles:
    - role: auth_keys

- name: 'Group hosts by distribution_major_version'
  hosts: 'tower,instance_group_*'
  tasks:
   - name: group hosts by distribution_major_version
     action: group_by key="{{ansible_distribution}}-{{ansible_distribution_major_version}}"

- name: 'Configure cluster ssh keys'
  hosts: 'tower:instance_group_*:isolated_group_*:database'
  roles:
    - { role: cluster_key_config, install_group: cluster_installer }

- name: 'Install cluster tower on installer instance'
  hosts: 'cluster_installer'
  gather_facts: no
  become: true
  become_method: sudo
  roles:
    - role: awx_setup

- name: Install specific version of ansible-runner (if applies)
  hosts: tower
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: ansible_runner
      when: awx_ansible_runner_url is defined and awx_ansible_runner_url != ''

- name: Install specific version of ansible-runner (if applies)
  hosts: isolated_group*
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: ansible_runner
      vars:
        isolated: true
      when: awx_ansible_runner_url is defined and awx_ansible_runner_url != ''

- name: 'install and configure haproxy'
  hosts: 'haproxy'
  roles:
    - role: haproxy
  gather_facts: no
  become: true
  become_method: sudo

# Only do this if/when haproxy host exists in the inventory
- name: 'Make Tower instances aware of upstream proxy'
  hosts: tower
  tasks:
    - name: "Tell tower to honor upstream forwarded for port and host headers"
      template:
        src: "templates/load_balancer.py.j2"
        dest: "/etc/tower/conf.d/load_balancer.py"
      when: "'haproxy' in hostvars.keys()"

- name: 'Configure firewall rules for isolated groups'
  hosts: 'isolated_group_protected:managed_hosts'
  become: true
  become_method: sudo
  tasks:
    - include_role:
        name: isolated_group_firewall_rules
      when: awx_apply_isolated_groups_fw_rules | default(true) | bool

- name: Remove IPV4
  hosts: tower
  tasks:
    - include_role:
        name: ipv6
      when: awx_ipv6_deployment | default(false) | bool

    - name: Save ipv6 to name resolution locally
      become: true
      delegate_to: localhost
      blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars[item]["ansible_default_ipv6"]["address"] }} {{ hostvars[item]["inventory_hostname"] }}
      with_items: '{{ groups["tower"] }}'
      when: awx_ipv6_deployment | default(false) | bool
