---
- name: 'Deploy cloud hosts'
  hosts: local
  roles:
    - { role: deploy_cloud }

- name: 'Dynamically create host groups'
  hosts: 'primary'
  tasks:
   - name: group hosts by distribution_major_version
     action: group_by key="{{ansible_distribution}}-{{ansible_distribution_major_version}}"

- name: 'Install Tower'
  hosts: 'primary'
  gather_facts: no
  sudo: yes
  roles:
    - { role: awx_setup }
