---
#
# Create remote hosts
#
- name: create instance(s)
  hosts: local

  roles:
    - role: create_ec2
    - role: create_rds
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.ha'
