---
# This playbook launches systems in the cloud and installs ansible

- name: 'deploy cloud instances'
  hosts: local
  roles:
    - { role: deploy_cloud }

- name: 'install ansible'
  hosts: cloud
  sudo: yes
  roles:
    - { role: packages }
