---
- name: create instance(s)
  hosts: local

  roles:
    - role: create_ec2
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.ldap'

- name: 'Install tower'
  hosts: 'primary'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: awx_setup

- name: 'Install ldap'
  hosts: 'ldap'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - role: bennojoy.openldap_server
      openldap_server_ldif: 'templates/tower-ldap.ldif.j2'
      openldap_server_rootpw: 'fo0m4nchU'
      openldap_server_enable_ssl: false

- name: 'Configure Tower to authenticate using LDAP'
  hosts: 'primary'
  gather_facts: no
  become: true
  become_method: sudo
  tasks:
    - name: Install Tower LDAP configuration file
      template:
        src: templates/tower-ldap.py.j2
        dest: /etc/tower/conf.d/ldap.py
        backup: yes

    - name: Restart ansible tower
      command: ansible-tower-service restart
