---
- name: Deploy cloud hosts
  hosts: localhost
  tasks:
    - include_tasks: openstack.yml
      with_items:
        - {name: '{{ lookup("env", "INSTANCE_NAME_PREFIX") | default("rhel8-osp") }}-rhel8', groups: 'tower' }

    - include_role:
        name: save_inventory_rhel8
      vars:
        my_inventory_file: '{{inventory_dir}}/inventory.log'

- name: Setup before proceeding
  hosts: tower
  become: yes
  environment:
    PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
  tasks:
    - copy:
        src: redhat.repo
        dest: /etc/yum.repos.d/redhat.repo

- name: 'Add authorized keys on database'
  hosts: 'database'
  roles:
    - role: auth_keys

- name: 'Dynamically create host groups'
  hosts: 'tower'
  tasks:
    - name: group hosts by distribution_major_version
      group_by:
        key: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
      changed_when: false

- name: Enable FIPS for isolated nodes
  hosts: 'tower'
  tasks:
    - name: Run FIPS Role
      include_role:
        name: fips
      when: "'7.5' in ansible_distribution_version and fips_enabled | default(true) | bool"

- name: 'Install Tower'
  hosts: 'tower'
  gather_facts: no
  become: true
  become_method: sudo
  environment:
    PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
  roles:
    - { role: awx_setup_rhel8 }

- name: Install specific version of ansible-runner (if applies)
  hosts: tower
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: ansible_runner
      when: awx_ansible_runner_url is defined and awx_ansible_runner_url != ''
