---
- name: create instance(s)
  hosts: local
  roles:
    - role: create_ec2
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.haproxy'

- name: 'Add authorized keys on cloud instance'
  hosts: 'haproxy'
  roles:
    - role: auth_keys

- name: 'install and configure haproxy'
  hosts: 'haproxy'
  roles:
    - role: haproxy
  gather_facts: no
  become: true
  become_method: sudo
