---
- name: 'Deploy cloud hosts'
  hosts: local
  roles:
    - { role: deploy_cloud }

- name: 'Add authorized keys on database'
  hosts: 'database'
  roles:
    - role: auth_keys

- name: 'Dynamically create host groups'
  hosts: 'tower'
  tasks:
    - name: group hosts by distribution_major_version
      group_by:
        key: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
      changed_when: false

- name: Enable FIPS for isolated nodes
  hosts: 'tower'
  tasks:
    - name: Run FIPS Role
      include_role:
        name: fips
      when: "'7.5' in ansible_distribution_version and {{ fips_enabled|default(true) }}"

- name: 'Install Tower'
  hosts: 'tower'
  gather_facts: no
  become: true
  become_method: sudo
  roles:
    - { role: awx_setup }
