---
- name: create instance(s)
  hosts: local
  roles:
    - role: create_ec2
    - role: create_rds
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.ha'

- name: 'Add authorized keys on non-installer instances'
  hosts: 'secondary:tower:database:haproxy:!ha_installer'
  roles:
    - role: auth_keys

- name: 'Group hosts by distribution_major_version'
  hosts: 'tower,primary,secondary'
  tasks:
   - name: group hosts by distribution_major_version
     action: group_by key="{{ansible_distribution}}-{{ansible_distribution_major_version}}"

- name: 'Configure cluster ssh keys'
  hosts: 'tower:database'
  roles:
    - role: cluster_key_config

- name: 'Install ha tower on installer instance'
  hosts: 'ha_installer,primary'
  gather_facts: no
  become: true
  become_method: sudo
  roles:
    - role: awx_setup

- name: 'install and configure haproxy'
  hosts: 'haproxy'
  roles:
    - role: haproxy
  gather_facts: no
  become: true
  become_method: sudo
