---
- name: create instance(s)
  hosts: local

  roles:
    - role: create_ec2
    - role: create_rds
    - role: save_inventory
      my_inventory_file: '{{inventory_dir}}/inventory.ha'

- name: 'Group hosts by distribution_major_version'
  hosts: 'primary'
  tasks:
   - name: group hosts by distribution_major_version
     action: group_by key="{{ansible_distribution}}-{{ansible_distribution_major_version}}"

- name: 'Add authorized keys on secondaries'
  hosts: 'secondary'
  roles:
    - role: auth_keys

- name: 'Install tower on primary instances'
  hosts: 'primary'
  gather_facts: no
  become: true
  become_method: sudo
  roles:
    - role: awx_setup
