---
#
# Create remote hosts
#
- hosts: local
  roles:
    - { role: deploy_cloud }

#
# Dynamically create host groups based on 'distribution-version'
#
- hosts: '!local'
  tasks:
   - name: group hosts by distribution_major_version
     action: group_by key="{{ansible_distribution}}-{{ansible_distribution_major_version}}"

#
# Install AWX
#
- hosts: '!local'
  gather_facts: no
  sudo: yes
  roles:
    - { role: awx_setup }
