---
# This playbook launches systems in the cloud and installs ansible

- name: 'deploy cloud instances'
  hosts: local
  roles:
    - { role: deploy_cloud }

- name: 'install ansible'
  hosts: cloud
  sudo: yes
  roles:
    - { role: packages }

- name: 'reset tower admin password (optional)'
  hosts: cloud
  sudo: yes
  vars:
    admin_password: fo0m4nchU
  tasks:
    - name: determine if awx is installed
      shell: awx-manage --help
      ignore_errors: true
      register: is_awx_installed

    - name: reset admin_password
      shell: echo "from django.contrib.auth.models import User; usr = User.objects.get(username='admin'); usr.set_password('{{ admin_password }}'); usr.save();" | awx-manage shell
      sudo_user: awx
      when: is_awx_installed|success

    - name: restart awx-celeryd
      supervisorctl: name=awx-celeryd state=restarted
      when: is_awx_installed|success

    - name: restart awx-callback-receiver
      supervisorctl: name=awx-callback-receiver state=restarted
      when: is_awx_installed|success

    - name: restart apache2
      service: name=apache2 state=restarted
      when: is_awx_installed|success

