---
# This playbook deploys the AWX application (database, web and worker) to a
# multiple platforms across multiple cloud providers.

#
# Create remote hosts
#
- hosts: local
  connection: local
  roles:
    - { role: destroy_cloud }
