---
ec2_public_key: '~/.ssh/id_rsa.jenkins.pub'

ec2_images:
    # CentOS 6.5, 6.6 images not produced by CentOS (1/5/15)
    - {'name': 'centos-6.5-x86_64',      'user': 'root',        'id': 'ami-8997afe0', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    # Latest CentOS6: need to confirm that the ami id remains valid when the image is updated
    - {'name': 'centos-6.latest-x86_64', 'user': 'centos',      'id': 'ami-57cd8732', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'centos-7.0-x86_64',      'user': 'centos',      'id': 'ami-96a818fe', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    # Latest CentOS7: need to confirm that the ami id remains valid when the image is updated
    - {'name': 'centos-7.latest-x86_64', 'user': 'centos',      'id': 'ami-61bbf104', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'rhel-6.5-x86_64',        'user': 'ec2-user',    'id': 'ami-8d756fe4', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'rhel-6.6-x86_64',        'user': 'ec2-user',    'id': 'ami-aed06ac6', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'rhel-6.7-x86_64',        'user': 'ec2-user',    'id': 'ami-0d28fe66', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'rhel-7.0-x86_64',        'user': 'ec2-user',    'id': 'ami-a8d369c0', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'rhel-7.1-x86_64',        'user': 'ec2-user',    'id': 'ami-12663b7a', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'rhel-7.2-x86_64',        'user': 'ec2-user',    'id': 'ami-2051294a', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'ubuntu-12.04-x86_64',    'user': 'ubuntu',      'id': 'ami-61930c76', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'ubuntu-14.04-x86_64',    'user': 'ubuntu',      'id': 'ami-20d3fc4a', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'ol-6.7-x86_64',          'user': 'ec2-user',    'id': 'ami-e9c98683', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }
    - {'name': 'ol-7.2-x86_64',          'user': 'ec2-user',    'id': 'ami-b9c38ad3', 'type': 'm3.large', 'groups': 'tower', 'security_group': 'Tower' }

ec2_security_groups:
    - name: Tower
      description: Security group for Tower instances
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
