---
instance_name_prefix: "{{ lookup('env','USER') }}-tower-ldap"

my_inventory_file: '{{inventory_dir}}/inventory.ldap'

#
# Images used for HA testing
#

ec2_images:
    - {'name': 'ldap-primary-centos-6.5-x86_64',   'user': 'root',     'id': 'ami-8997afe0', 'type': 'm3.large', 'groups': 'primary',   'security_group': 'Tower'}
    - {'name': 'ldap-openldap-centos-7.0-x86_64',  'user': 'centos',   'id': 'ami-96a818fe', 'type': 'm3.large', 'groups': 'ldap',   'security_group': 'LDAP'}

ec2_security_groups:
    - name: Tower
      description: Security group for Tower instances
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0

    - name: LDAP
      description: Security group for openldap server
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 389
          to_port: 389
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 636
          to_port: 636
          cidr_ip: 0.0.0.0/0
