---

# EC2 options for windows instances.
win_ec2_region: 'us-east-1'
win_ec2_instance_type: 'm3.medium'
win_ec2_security_group: 'Ansible WinRM'
win_ec2_key_name: 'ansible-winrm'
win_ec2_public_key: '~/.ssh/id_rsa.pub'
win_ec2_private_key: '~/.ssh/id_rsa'

# Available windows ec2 images.
win_ec2_images:
  - {'name': 'server-2008',       'user': 'Administrator', 'id': 'ami-b89d0cd0'}
  - {'name': 'server-2008-r2',    'user': 'Administrator', 'id': 'ami-b68819de'}
  - {'name': 'server-2012',       'user': 'Administrator', 'id': 'ami-e49a0b8c'}
  - {'name': 'server-2012-r2',    'user': 'Administrator', 'id': 'ami-c49c0dac'}
