---
instance_name_prefix: "{{ lookup('env','USER') }}-tower-isolated-groups"
my_inventory_file: '{{inventory_dir}}/inventory.ha'
ha_install: true

ec2_images:
    #- {'name': 'haproxy-rhel-7.2-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'haproxy', 'security_group': 'tower-ha'}
    - {'name': 'ha-1-rhel-7.2-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'tower, ha_installer, instance_group_ordinary_instances, instance_group_partition_1, instance_group_1', 'security_group': 'tower-ha'}
    - {'name': 'ha-2-rhel-7.2-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'instance_group_ordinary_instances, instance_group_controller, instance_group_partition_2, instance_group_2, instance_group_4', 'security_group': 'tower-ha'}
    - {'name': 'ha-3-rhel-7.2-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'tower, instance_group_ordinary_instances, instance_group_controller, instance_group_partition_2, instance_group_3, instance_group_4', 'security_group': 'tower-ha'}
    - {'name': 'ha-4-rhel-7.2-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'isolated_group_protected', 'controller': 'controller', 'security_group': 'tower-ha'}
    - {'name': 'ha-5-rhel-7.2-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'isolated_group_protected', 'controller': 'controller', 'security_group': 'tower-ha'}
    - {'name': 'ha-pg-rhel-7.2.-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'database', 'security_group': 'tower-ha'}
    - {'name': 'ha-managed-host-rhel-7.2.-x86_64', 'user': 'ec2-user', 'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'managed_hosts', 'security_group': 'tower-ha'}

ec2_security_groups:
    - name: tower-ha
      description: Security group for Tower HA instances
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 389
          to_port: 389
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 1936
          to_port: 1936
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 4369
          to_port: 4369
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5432
          to_port: 5432
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5672
          to_port: 5672
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 15672
          to_port: 15672
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 25672
          to_port: 25672
          cidr_ip: 0.0.0.0/0
    - name: tower-isolated-group
      description: Security group for Tower HA isolated groups
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

# HA installer installs postgres so this should be done manually atm
# rds_images:
#     - name: 'tower'
#       db_name: 'awx'
#       db_engine: '{{rds_db_engine}}'
#       engine_version: '{{rds_engine_version}}'
#       instance_type: '{{rds_instance_type}}'
#       size: '{{rds_size}}'
#       groups: 'postgres'
