---

create_ec2_assign_public_ip: true
create_ec2_vpc_id: vpc-552da032
create_ec2_vpc_subnet_id: subnet-9cdddbb0

user_data_install_py2: &install_py2
  "{{ lookup('file', 'files/install_py2.sh') }}"

ec2_images:
    - {'name': 'centos-7.0-x86_64',      'user': 'centos',      'id': 'ami-96a818fe', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    # Latest CentOS7: need to confirm that the ami id remains valid when the image is updated
    - {'name': 'centos-7.latest-x86_64', 'user': 'centos',      'id': 'ami-9887c6e7', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'rhel-7.0-x86_64',        'user': 'ec2-user',    'id': 'ami-645bae0c', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'rhel-7.1-x86_64',        'user': 'ec2-user',    'id': 'ami-10663b78', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'rhel-7.2-x86_64',        'user': 'ec2-user',    'id': 'ami-2a532b40', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'rhel-7.3-x86_64',        'user': 'ec2-user',    'id': 'ami-a33668b4', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'rhel-7.4-x86_64',        'user': 'ec2-user',    'id': 'ami-7a96b801', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'rhel-7.5-x86_64',        'user': 'ec2-user',    'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'rhel-7.6-x86_64',        'user': 'ec2-user',    'id': 'ami-0a0e0aebb1b6a5ff0', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'ubuntu-14.04-x86_64',    'user': 'ubuntu',      'id': 'ami-ec601593', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'ubuntu-16.04-x86_64',    'user': 'ubuntu',      'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower', 'user_data': *install_py2 }
    - {'name': 'ol-7.2-x86_64',          'user': 'ec2-user',    'id': 'ami-b9c38ad3', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'ol-7.3-x86_64',          'user': 'ec2-user',    'id': 'ami-7c4b7e6b', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'ol-7.4-x86_64',          'user': 'ec2-user',    'id': 'ami-75bde60f', 'type': 'm3.medium', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }
    - {'name': 'ol-7.5-x86_64',          'user': 'ec2-user',    'id': 'ami-3485114b', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower' }

_ec2_elastic_ips:
    - {'name': 'rhel-7.2-x86_64', 'eip': '35.169.222.27'}
    - {'name': 'rhel-7.4-x86_64', 'eip': '35.170.40.126'}
    - {'name': 'rhel-7.5-x86_64', 'eip': '52.54.81.210'}
    - {'name': 'centos-7.latest-x86_64', 'eip': '54.86.26.131'}

ec2_security_groups:
    - name: Tower
      description: Security group for Tower instances
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5432
          to_port: 5432
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: udp
          from_port: 9001
          to_port: 9001
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 9001
          to_port: 9001
          cidr_ip: 0.0.0.0/0
