---
instance_name_prefix: 'jenkins-tower-ha'

my_inventory_file: '{{inventory_dir}}/inventory.ha'

#
# Images used for HA testing
#

ec2_images:
    - {'name': 'ha-primary-centos-6.5-x86_64',     'user': 'root',     'id': 'ami-8997afe0', 'type': 'm3.medium', 'groups': 'primary'}
    - {'name': 'ha-secondary-rhel-6.5-x86_64',     'user': 'ec2-user', 'id': 'ami-8d756fe4', 'type': 'm3.medium', 'groups': 'secondary'}
    - {'name': 'ha-secondary-rhel-7.0-x86_64',     'user': 'ec2-user', 'id': 'ami-785bae10', 'type': 'm3.medium', 'groups': 'secondary'}
    - {'name': 'ha-secondary-ubuntu-12.04-x86_64', 'user': 'ubuntu',   'id': 'ami-2ccc7a44', 'type': 'm3.medium', 'groups': 'secondary'}
    - {'name': 'ha-secondary-ubuntu-14.04-x86_64', 'user': 'ubuntu',   'id': 'ami-8caa1ce4', 'type': 'm3.medium', 'groups': 'secondary'}
    # - {'name': 'ha-mongo-centos-7.0-x86_64',       'user': 'centos',   'id': 'ami-96a818fe', 'type': 'm3.medium', 'groups': 'mongodb' }


rds_images:
    - name: 'tower'
      db_name: 'awx'
      db_engine: '{{rds_db_engine}}'
      engine_version: '{{rds_engine_version}}'
      instance_type: '{{rds_instance_type}}'
      size: '{{rds_size}}'
      groups: 'postgres'
