---
instance_name_prefix: "{{ lookup('env','USER') }}-tower-isolated-groups"
my_inventory_file: '{{inventory_dir}}/inventory.cluster'
cluster_install: true

create_ec2_assign_public_ip: true
create_ec2_vpc_id: vpc-552da032
create_ec2_vpc_subnet_id: subnet-9cdddbb0

user_data_install_py2: &install_py2
  "{{ lookup('file', 'files/install_py2.sh') }}"

ec2_images:
    # - {'name': 'haproxy-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'haproxy', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-1-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'tower, cluster_installer, instance_group_ordinary_instances, instance_group_partition_1, instance_group_1', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-2-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_partition_1, instance_group_2, instance_group_6', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-3-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_future_controller, instance_group_partition_2, instance_group_3, instance_group_6, instance_group_7', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-4-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_controller, instance_group_partition_2, instance_group_4, instance_group_7', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-5-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_controller, instance_group_partition_2, instance_group_5, instance_group_7', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-6-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'isolated_group_protected', 'controller': 'controller', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-7-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'isolated_group_protected', 'controller': 'controller', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-pg-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'database', 'security_group': 'tower-cluster'}
    - {'name': 'cluster-managed-host-rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm3.medium', 'groups': 'managed_hosts', 'security_group': 'tower-cluster'}

    - {'name': 'cluster-1-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'tower,cluster_installer,instance_group_ordinary_instance,instance_group_partition1,instance_group_1', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-2-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_partition_1, instance_group_2, instance_group_6', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-3-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_future_controller, instance_group_partition_2, instance_group_3, instance_group_6, instance_group_7', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-4-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_controller, instance_group_partition_2, instance_group_4, instance_group_7', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-5-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'tower, instance_group_ordinary_instances, instance_group_controller, instance_group_partition_2, instance_group_5, instance_group_7', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-6-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'isolated_group_protected', 'controller': 'controller', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-7-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'isolated_group_protected', 'controller': 'controller', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-pg-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm5.large', 'groups': 'database', 'security_group': 'tower-cluster', 'user_data': *install_py2 }
    - {'name': 'cluster-managed-host-ubuntu-16.04-x86_64', 'user': 'ubuntu', 'id': 'ami-077b0e78', 'type': 'm3.medium', 'groups': 'managed_hosts', 'security_group': 'tower-cluster', 'user_data': *install_py2 }

ec2_security_groups:
    - name: tower-cluster
      description: Security group for Tower instances
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 389
          to_port: 389
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 1936
          to_port: 1936
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 4369
          to_port: 4369
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5432
          to_port: 5432
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5672
          to_port: 5672
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 15672
          to_port: 15672
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 25672
          to_port: 25672
          cidr_ip: 0.0.0.0/0
    - name: tower-isolated-group
      description: Security group for Tower HA isolated groups
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

# HA installer installs postgres so this should be done manually atm
# rds_images:
#     - name: 'tower'
#       db_name: 'awx'
#       db_engine: '{{rds_db_engine}}'
#       engine_version: '{{rds_engine_version}}'
#       instance_type: '{{rds_instance_type}}'
#       size: '{{rds_size}}'
#       groups: 'postgres'
