---
user_data_install_py2: &install_py2
  "{{ lookup('file', 'files/install_py2.sh') }}"

ec2_images:
    - {'name': 'centos-7.latest-x86_64', 'user': 'centos',      'id': 'ami-61bbf104', 'type': 'm3.medium', 'groups': 'tower,primary', 'security_group': 'Tower' }
    - {'name': 'rhel-7.2-x86_64',        'user': 'ec2-user',    'id': 'ami-2051294a', 'type': 'm3.medium', 'groups': 'tower,primary', 'security_group': 'Tower' }
    - {'name': 'ubuntu-14.04-x86_64',    'user': 'ubuntu',      'id': 'ami-20d3fc4a', 'type': 'm3.medium', 'groups': 'tower,primary', 'security_group': 'Tower' }
    - {'name': 'ol-7.2-x86_64',          'user': 'ec2-user',    'id': 'ami-b9c38ad3', 'type': 'm3.medium', 'groups': 'tower,primary', 'security_group': 'Tower' }

ec2_security_groups:
    - name: Tower
      description: Security group for Tower instances
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
