---
instance_name_prefix: "{{ lookup('env','USER') }}-freeipa"
my_inventory_file: '{{inventory_dir}}/inventory.freeipa'

ec2_images:
    - {'name': 'freeipa - rhel-7.4-x86_64', 'user': 'ec2-user', 'id': 'ami-c998b6b2', 'type': 'm3.medium', 'groups': 'freeipa', 'security_group': 'freeipa'}

ec2_security_groups:
    - name: freeipa
      description: Security group for FreeIPA instance allowing LDAP, ssh, and webUI access
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 389
          to_port: 389
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0