---
- name: 'Gather facts'
  hosts: '!local'
  tasks:
    - name: group hosts by distribution_major_version
      action: group_by key="{{ansible_distribution}}-{{ansible_distribution_major_version}}"

- name: 'Install Tower'
  hosts: '!local'
  gather_facts: false
  sudo: true
  roles:
    - {role: awx_setup}

# Attempt to catch problems caused by reboots such as https://github.com/ansible/tower/issues/3521
- name: Reboot systems to ensure tower works after reboot
  # Not all issues may be caught by ansible-tower-service status but at least we know the server "should" be up by then
  become: true
  hosts: 'tower'
  tasks:
    - name: Reboot tower
      reboot:
        test_command: 'ansible-tower-service status'
        msg: 'Reboot initiated by run of tower-qa/playbooks/install-tower.yml'
