---
# This playbook installs an LDAP server to work with tower

- hosts: all

#
# Install LDAP
#
  roles:
    - role: bennojoy.openldap_server
      openldap_server_ldif: 'templates/tower-ldap.ldif.j2'
      openldap_server_rootpw: 'fo0m4nchU'
      openldap_server_enable_ssl: false

  tasks:
    - name: transfer over LDAP configuration file
      template:
        src: templates/tower-ldap.py.j2
        dest: /etc/tower/conf.d/ldap.py
        backup: yes

    - name: restart ansible tower
      service:
        name: ansible-tower
        state: restarted
