---
# This playbook installs ansible to multiple platforms across multiple cloud
# providers.

#
# Create remote hosts
#
- hosts: local
  roles:
    - { role: create_ec2 }
    - { role: save_inventory }

#
# Dynamically create host groups based on distribution
#
- hosts: all
  tasks:
   - name: group hosts by distribution
     action: group_by key={{ansible_distribution}}

#
# Install ansible
#
- hosts: '!local'
  sudo: yes
  roles:
    - { role: ansible_install }

#
# Destroy remote hosts
#
- hosts: local
  roles:
    - { role: create_ami }
    - { role: terminate_ec2, delete_on_start: true }

