---
# This playbook open rdesktop connection(s) to windows instance(s).

- name: open rdesktop to selected instance(s)
  hosts: windows
  gather_facts: false
  tasks:
    - name: open rdesktop
      local_action: command rdesktop
        -u {{ hostvars[inventory_hostname]['ansible_ssh_user']|quote }}
        #-d ANSIBLE
        -p {{ hostvars[inventory_hostname]['ansible_ssh_pass']|quote }}
        -T {{ inventory_hostname|quote }} -0 -g 1280x800
        '{{ ansible_ssh_host|default(inventory_hostname) }}'
      ignore_errors: true
