#
# Expected variables in this play
#
#   |--------------------|-------------|---------------------|
#   | Name               | Description | Example             |
#   |--------------------|-------------|---------------------|
#   | rhel_cloud_image   |             | 'RHEL-7.6-Beta-1.2' |
#   | supported_versions |             | ['devel', 3.3.0']   |
#   | node_flavor        |             | m5.large            |
#   | node_keypair       |             | mykeypair           |
#   | admin_password     |             | password            |
#   | pg_password        |             | password            |
#   | rhsm_username      |             | jdoe@redhat.com     |
#   | rhsm_password      |             | password            |
#   | rhsm_pool_ids      |             | 890fewqrewqrew098   |
#   | working_dir        |             | /tmp                |
#   |--------------------|-------------|---------------------|
#
---
- name: Prepare the cloud-provider infrastructure to run our tests
  hosts: localhost
  tasks:

    - name: Define the rhel_version fact
      set_fact:
        rhel_version: '{{ rhel_cloud_image.split("/")[4] }}'

    - name: Retrieve the pre-release cloud image
      get_url:
        url: '{{ rhel_cloud_image }}'
        dest: '{{ working_dir }}/{{ rhel_cloud_image | basename }}'

    - name: Load the pre-release cloud image on the cloud
      os_image:
        name: '{{ rhel_version }}'
        container_format: bare
        disk_format: qcow2
        filename: '{{ working_dir }}/{{ rhel_cloud_image | basename }}'

    - name: Manage Security Group
      os_security_group:
        name: tower

    - name: Manage Security group's firewall rule
      os_security_group_rule:
        security_group: tower
        protocol: tcp
        port_range_min: '{{ item }}'
        port_range_max: '{{ item }}'
        remote_ip_prefix: 0.0.0.0/0
      loop:
        - 22
        - 80
        - 443

    - name: Spawn and run test for each supported Tower version
      include_tasks: rhel-prerelease-testing-node.yml
      loop: '{{ supported_versions }}'
      loop_control:
        loop_var: tower_version
