---
# Tasks to install awx-setup package-related dependencies on EL systems

- include: rhn.yml
  when: rhn_method is defined and ansible_pkg_mgr == 'yum' and ansible_distribution == 'RedHat'

# Mirrors don't always do the right thing ... retry until the package installs
- name: install epel-release
  shell: rpm -q epel-release || rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
  register: epel_task
  until: epel_task.rc == 0
  when: ansible_pkg_mgr == 'yum' and ansible_distribution == 'RedHat'

- name: install playbook dependencies
  yum: name={{item}} state=installed
  with_items:
    - libselinux-python
  when: ansible_pkg_mgr == 'yum' and ansible_distribution == 'RedHat'

# install ansible nightly rpm repo (optional)

- name: install custom ansible repository
  template: src=files/ansible_yum_epel.repo.j2 dest=/etc/yum.repos.d/ansible.repo
  register: yum_repo
  when: ansible_pkg_mgr == 'yum' and ansible_distribution == 'RedHat' and ansible_repo_url is defined

- name: yum clean cached ansible repository information
  command: yum clean all --disablerepo=* --enablerepo=ansible-nightly
  when: ansible_pkg_mgr == 'yum' and ansible_distribution == 'RedHat' and yum_repo is defined and yum_repo.changed

# install ansible

- name: install nightly ansible rpm
  # shell: yum -y --enablerepo=updates-testing,epel-testing,ansible-nightly install ansible
  yum: name=ansible enablerepo=*-testing,ansible-nightly state=installed
  when: ansible_pkg_mgr == 'yum' and ansible_distribution == 'RedHat' and ansible_repo_url is defined

- name: install ansible rpm
  # shell: yum -y --enablerepo=updates-testing,epel-testing install ansible
  yum: name=ansible enablerepo=*-testing state=installed
  when: ansible_pkg_mgr == 'yum' and ansible_distribution == 'RedHat' and ansible_repo_url is defined
