---
# Download ansible-tower-setup and run the setup playbook

- name: download ansible-tower-setup tarball
  get_url: url={{aw_repo_url}}/{{awx_setup_path}} dest=/tmp mode=0640
  register: tarball

- name: untar ansible-tower-setup
  shell: tar -xvf {{tarball.dest}} --transform "s|^[^/]*|setup|" chdir=/tmp

- name: is awx already installed?
  stat: path=/etc/tower/awx.cert
  register: is_awx_installed

- name: disable sudo requiretty for root
  lineinfile: dest=/etc/sudoers
     state=present
     regexp='^Defaults:root'
     line='Defaults:root !requiretty'

- name: create tower_setup_conf.yml file
  template: src=tower_setup_conf.yml.j2 dest=/tmp/setup/tower_setup_conf.yml
  when: not is_awx_installed.stat.exists or awx_upgrade

- name: run configure script
  command: ./configure -o tower_setup_conf.yml
     chdir=/tmp/setup
  when: not is_awx_installed.stat.exists or awx_upgrade

- name: create vars.yml file
  template: src=vars.yml.j2 dest=/tmp/setup/vars.yml
  when: not is_awx_installed.stat.exists or awx_upgrade

- name: setup.sh
  command: ./setup.sh -e @vars.yml
     chdir=/tmp/setup
     # creates=/etc/tower/awx.cert
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  when: not is_awx_installed.stat.exists or awx_upgrade
