---
# Download ansible-tower-setup and run the setup playbook

- name: download ansible-tower-setup tarball
  get_url: url={{aw_repo_url}}/{{awx_setup_path}} dest=/tmp mode=0640
  register: tarball

- name: untar ansible-tower-setup
  shell: tar -xvf {{tarball.dest}} --transform "s|^[^/]*|setup|" chdir=/tmp

- name: is awx already installed?
  stat: path=/etc/tower/awx.cert
  register: is_awx_installed
  ignore_errors: yes

- name: disable sudo requiretty for root
  lineinfile: dest=/etc/sudoers
     state=present
     regexp='^Defaults:root'
     line='Defaults:root !requiretty'

- name: create tower_setup_conf.yml
  template: src=tower_setup_conf.yml.j2 dest=/tmp/setup/tower_setup_conf.yml
  when: not is_awx_installed.stat.exists or awx_upgrade

- name: create awx_vars.yaml
  template: src=awx_vars.yml.j2 dest=/tmp/setup/awx_vars.yaml
  when: not is_awx_installed.stat.exists or awx_upgrade

- name: setup.sh
  command: ./setup.sh -e @awx_vars.yaml
     chdir=/tmp/setup
     # creates=/etc/tower/awx.cert
  when: not is_awx_installed.stat.exists or awx_upgrade
