---

- name: install ad domain services
  win_feature:
    name: AD-Domain-Services
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes
  register: install_ad_domain_services

- name: wait for host to become available again
  local_action: wait_for host={{ ansible_ssh_host|default(inventory_hostname) }} port={{ ansible_ssh_port|default(5986) }} delay=10 timeout=300
  when: install_ad_domain_services|changed

- name: ping server after ad domain services installed
  action: win_ping
  when: install_ad_domain_services|changed

- name: run script to configure ad domain services
  script: deploy_ad_ds.ps1 -safeModeAdministratorPassword {{ win_ad_safe_mode_administrator_password|quote }} -domainName {{ win_ad_domain_name|quote }} -netbiosName {{ win_ad_netbios_name|quote }}
  register: deploy_ad_ds_result
  failed_when: deploy_ad_ds_result|failed or deploy_ad_ds_result.stderr
  changed_when: "'DCPromo' in deploy_ad_ds_result.stdout"

- name: add test users to ad
  win_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: win_ad_users
