---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tower-qe-integration
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "secrets", "configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tower-qe-integration
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tower-qe-integration