# This creates an Ingress that exposes nginx-app-proxy. That is the mechanism that allows for
# Dynamic resolution based on the URL scheme
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-app-proxy
spec:
  tls:
    - hosts:
      - 'services.k8s.tower-qe.testing.ansible.com'
      secretName: tower-qe-tls
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: nginx-app-proxy
            servicePort: 80
