apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: tower-qe-services-tls
 namespace: default
spec:
 secretName: tower-qe-tls
 issuerRef:
   name: letsencrypt-prod
   kind: Issuer
 dnsNames:
   - '*.services.k8s.tower-qe.testing.ansible.com'
 acme:
   config:
     - dns01:
         provider: route53
       domains:
         - '*.services.k8s.tower-qe.testing.ansible.com'
